# Generated by Django 4.1.7 on 2023-03-01 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projid', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=30)),
                ('deadline', models.DateField()),
                ('completed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=80)),
                ('done', models.BooleanField()),
                ('projid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectp.project')),
            ],
        ),
    ]
